project_path: "/Users/alexiy/Projects/boilermakexi"
db_path: "data/db.json"
match_threshold: 0.1
add_threshold: 0.03
threshold_weights:
  - 0.5 # bottom of palm
  # thumb starts
  - 0.7 # start of thim
  - 0.9
  - 4.1
  - 5
  # second finger starts
  - 0.7 # start of thim
  - 0.9
  - 4.1
  - 5
  # third finger starts
  - 0.7 # start of thim
  - 0.9
  - 4.1
  - 5
  # fourth finger starts
  - 0.7 # start of thim
  - 0.9
  - 4.1
  - 5
  # fifth finger starts
  - 0.7 # start of thim
  - 0.9
  - 4.1
  - 5