add_threshold: 0.03
break_early: 0.03
dataset_path: data/blank.csv
db_path: data/new_db.json
debounce_time_direction_depth: 0.2
debounce_time_inference: 0.2
epochs: 500
inference_threads: 32
linear_bound: 2.5
match_threshold: 0.1
min_side_len_ratio: 10
min_train_steps: 100
model_save_path: data/model.pickle
output_classes: 4
project_path: /Users/jj/boilermakexi/Hand_Tracking
sample_count: 25
threads: 32
threshold_weights:
- 0.5
- 0.7
- 2.9
- 4.1
- 10
- 0.7
- 2.9
- 4.1
- 10
- 0.7
- 2.9
- 4.1
- 10
- 0.7
- 2.9
- 4.1
- 10
- 0.7
- 2.9
- 4.1
- 10
time_delta: 6
zoom_thresh: 0.07
